name: Deployment

on:
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://rakamin-mini-project.portalnesia.com
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/go/src/rakamin.com/rakamin-mini-project
            ./script.exp
            git pull origin main
            git status
            go mod tidy
            go build -o rakamin-mini-project main.go
            systemctl --user restart rakamin
            