on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: Security
jobs:
  GoSecurity:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master